"""add outbox retry tracking

Revision ID: 1c7a8cbf2d73
Revises: 665a09dd8a47
Create Date: 2026-09-08 08:27:03.605354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c7a8cbf2d73'
down_revision: Union[str, Sequence[str], None] = '665a09dd8a47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox_events', sa.Column('retry_count', sa.Integer(), nullable=False , server_default='0'))
    op.add_column('outbox_events', sa.Column('last_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outbox_events', 'last_error')
    op.drop_column('outbox_events', 'retry_count')
    # ### end Alembic commands ###
