"""create delivery assignments table

Revision ID: 82d1223f5016
Revises: c82d31a98da5
Create Date: 2026-09-06 13:00:44.421951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82d1223f5016'
down_revision: Union[str, Sequence[str], None] = 'c82d31a98da5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_assignments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('delivery_partner_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['delivery_partner_id'], ['delivery_partners.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', name='uq_delivery_assignment_order')
    )
    op.create_index(op.f('ix_delivery_assignments_delivery_partner_id'), 'delivery_assignments', ['delivery_partner_id'], unique=False)
    op.create_index(op.f('ix_delivery_assignments_order_id'), 'delivery_assignments', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_delivery_assignments_order_id'), table_name='delivery_assignments')
    op.drop_index(op.f('ix_delivery_assignments_delivery_partner_id'), table_name='delivery_assignments')
    op.drop_table('delivery_assignments')
    # ### end Alembic commands ###
